# Generated by Django 5.2.12 on 2026-04-19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraAlertSeverity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_key', models.CharField(max_length=50)),
                ('severity', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='low', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_severity_overrides', to='cameras.camera')),
            ],
            options={
                'indexes': [
                    models.Index(fields=['camera', 'model_key'], name='alerts_came_camera__8c7ec2_idx'),
                    models.Index(fields=['model_key'], name='alerts_came_model_k_93a083_idx'),
                ],
                'unique_together': {('camera', 'model_key')},
            },
        ),
    ]
