# Generated by Codex on 2026-06-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devlab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField(default=0)),
                ('content_type', models.CharField(default='image/jpeg', max_length=100)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
