# Generated by Django 5.2.12 on 2026-03-12 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelSetting',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_key', models.CharField(max_length=50)),
                ('payload', models.JSONField(default=dict)),
                ('confidence', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('error', 'Error'), ('unavailable', 'Unavailable')], default='ok', max_length=20)),
                ('detected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='cameras.camera')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='detection_d_created_512b08_idx'), models.Index(fields=['camera'], name='detection_d_camera__228523_idx')],
            },
        ),
        migrations.CreateModel(
            name='CameraModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_overrides', to='cameras.camera')),
                ('model_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.modelsetting')),
            ],
            options={
                'unique_together': {('camera', 'model_setting')},
            },
        ),
    ]
